# Generated by Django 2.0.4 on 2019-01-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testSubTable2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.DeleteModel(
            name='ServiceOrderCondition',
        ),
    ]
