# Generated by Django 2.0.4 on 2019-01-25 10:32

from django.db import migrations, models
import django.db.models.deletion
import testSubTable.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'user',
            },
            bases=(models.Model, testSubTable.models.UserShardMixin),
        ),
        migrations.CreateModel(
            name='User_2019_1',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testSubTable.User')),
            ],
            options={
                'verbose_name': 'User_2019_1',
                'verbose_name_plural': 'User_2019_1',
            },
            bases=('testSubTable.user',),
        ),
        migrations.CreateModel(
            name='User_2019_10',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testSubTable.User')),
            ],
            options={
                'verbose_name': 'User_2019_10',
                'verbose_name_plural': 'User_2019_10',
            },
            bases=('testSubTable.user',),
        ),
        migrations.CreateModel(
            name='User_2019_11',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testSubTable.User')),
            ],
            options={
                'verbose_name': 'User_2019_11',
                'verbose_name_plural': 'User_2019_11',
            },
            bases=('testSubTable.user',),
        ),
        migrations.CreateModel(
            name='User_2019_12',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testSubTable.User')),
            ],
            options={
                'verbose_name': 'User_2019_12',
                'verbose_name_plural': 'User_2019_12',
            },
            bases=('testSubTable.user',),
        ),
        migrations.CreateModel(
            name='User_2019_2',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testSubTable.User')),
            ],
            options={
                'verbose_name': 'User_2019_2',
                'verbose_name_plural': 'User_2019_2',
            },
            bases=('testSubTable.user',),
        ),
        migrations.CreateModel(
            name='User_2019_3',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testSubTable.User')),
            ],
            options={
                'verbose_name': 'User_2019_3',
                'verbose_name_plural': 'User_2019_3',
            },
            bases=('testSubTable.user',),
        ),
        migrations.CreateModel(
            name='User_2019_4',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testSubTable.User')),
            ],
            options={
                'verbose_name': 'User_2019_4',
                'verbose_name_plural': 'User_2019_4',
            },
            bases=('testSubTable.user',),
        ),
        migrations.CreateModel(
            name='User_2019_5',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testSubTable.User')),
            ],
            options={
                'verbose_name': 'User_2019_5',
                'verbose_name_plural': 'User_2019_5',
            },
            bases=('testSubTable.user',),
        ),
        migrations.CreateModel(
            name='User_2019_6',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testSubTable.User')),
            ],
            options={
                'verbose_name': 'User_2019_6',
                'verbose_name_plural': 'User_2019_6',
            },
            bases=('testSubTable.user',),
        ),
        migrations.CreateModel(
            name='User_2019_7',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testSubTable.User')),
            ],
            options={
                'verbose_name': 'User_2019_7',
                'verbose_name_plural': 'User_2019_7',
            },
            bases=('testSubTable.user',),
        ),
        migrations.CreateModel(
            name='User_2019_8',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testSubTable.User')),
            ],
            options={
                'verbose_name': 'User_2019_8',
                'verbose_name_plural': 'User_2019_8',
            },
            bases=('testSubTable.user',),
        ),
        migrations.CreateModel(
            name='User_2019_9',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testSubTable.User')),
            ],
            options={
                'verbose_name': 'User_2019_9',
                'verbose_name_plural': 'User_2019_9',
            },
            bases=('testSubTable.user',),
        ),
    ]
